package ActOne.runtime.model;

/*Generated by MPS */


public class Operator {

  private final boolean constructor;
  private final String name;

  public Operator(Boolean constructor, String name) {
    this.constructor = constructor;
    this.name = name;
  }

  @Override
  public String toString() {
    return this.name;
  }

}
