package ActOne.runtime.predefined;

/*Generated by MPS */

import ActOne.runtime.model.ITerm;
import ActOne.runtime.model.Operator;

public abstract class ANY {
  public static class Any extends ITerm {

    public Any(Operator operator, ITerm... terms) {
      super(operator, terms);
    }

    public Any(ITerm.Kind kind, String name) {
      super(kind, name);
    }
  }
}
